version: '3'

networks:
  backend:
    driver: bridge

volumes:
  pgsql:
    driver: local

services:
  node:
    tty: true
    image: node:16
    volumes:
      - ../:/var/www
    networks:
      - backend
    ports:
      - "${APPLICATION_PORT}:3000"

    working_dir: /var/www
    user: node

  pgsql:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./.data/pgsql:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
